### ISSUE TITLE
发现收藏和加购的bug

### ISSUE THREAD

**Issue by Xihaya** [Dcanmera/beetle#3]
我跑起来过后注册了两个用户，用户1发布了商品，用户2收藏加购在用户2的收藏加购里没有，反而用户1的加购和收藏里多了这个商品。
最后发现是sql语句的问题
修改的地方：shopcartProducts和findLike里的sql中的`up`.`user_id` = :userId'分别改成 `l`.`user_id` = :userId'和`s`.`user_id` = :userId'

**Comment by DCANMERA** [comment]
> 我跑起来过后注册了两个用户，用户1发布了商品，用户2收藏加购在用户2的收藏加购里没有，反而用户1的加购和收藏里多了这个商品。 最后发现是sql语句的问题 修改的地方：shopcartProducts和findLike里的sql中的`up`.`user_id` = :userId'分别改成 `l`.`user_id` = :userId'和`s`.`user_id` = :userId'

感谢指正，已修复🤞
